### PR TITLE
A myriad of updates.

### PR DESCRIPTION
**Pull request by avaidyam**
The updates are as follows:
- Migrated example app code from /ConcordeExample to /Example.
- Lion-like `TUIScrollKnob` that hide based on visibility settings.
- `TUITextRenderer` key bindings (MANY added).
- `TUITextRenderer` auto-scrolling if nested within a `TUIScrollView`.
- `TUITextRenderer` optional overflow ellipses (`...` added if the word is too long).
- Custom cursor and text selection color.
- `TUIScrollView` `-isBouncing` and `-stopThrowing`.
- Secure Text Field Entry.
- `TUIControl` tracking support (like UIKit's `UIControl`).
- KVO/Notifications in a few places, with a few added convenience properties and bug fixes.

Most of the credit goes to @michaelvillar.

### CODE REVIEW

**Comment by jspahrsummers** [comment]
This will not merge without conflicts, and is way, way too huge. Please try to partition the work into smaller feature branches that can be reviewed independently.

**Comment by dannygreg** [comment]
To help you out a little bit, pretty much every one of those bullet points you listed in the description should be in a separate pull request.

**Comment by avaidyam** [comment]
How do I do that? Github automatically clumped all of those commits into one pull request... :( Is there a way to split pull requests?

**Comment by dannygreg** [comment]
Do each unit of work on a separate branch and pull request those… that's how we work. 

There are other ways though, you can cherry pick commits for a pull request. Check out this [help doc](https://help.github.com/articles/using-pull-requests).

**Pull request closed without merging**
