### PR TITLE
TUIScrollView bug fixing

### PR DESCRIPTION
**Pull request by luosheng**
When `TUIScrollView` starts "throwing", it should respect its `contentInset`. The original code checks `self._pulling && _scrollViewFlags.didChangeContentInset` before updating its bounce values.

However, when it calls `self._pulling`, which is implemented by returning `_pull.xPulling || _pull.yPulling`, the `xPulling` and `yPulling` flags have already been reset to `NO` by the code blocks above it. So the condition evaluation is always `NO` and the code won't get a chance to execute.

I fix this by simply prefetching the pulling state of `TUIScrollView` before resetting it.

### CODE REVIEW

**Comment by avaidyam** [comment]
+1 Thanks!

**Comment by jspahrsummers** [comment]
:+1: This change seems good. Can you also add an explanatory comment to the implementation for future readers, though?

**Comment by luosheng** [comment]
Sure, it's done.

**Comment by jspahrsummers** [comment]
Thanks! :sparkles:

**Pull request merged**
