### PR TITLE
Add or remove the text view cursor based on -willMoveToWindow:

### PR DESCRIPTION
**Pull request by jspahrsummers**
We won't have a window in `-initWithFrame:`, so trying to do anything with the cursor there won't work.

CC @galaxas0

### CODE REVIEW

**Comment by avaidyam** [comment]
LOL. I might have messed that up just a bit. Sorry. :P

**Comment by dannygreg** [comment]
:shipit:

**Comment by avaidyam** [comment]
Is that a hamster... In a suit and top hat?  

## 

Aditya.

**Comment by jwilling** [comment]
@galaxas0 http://shipitsquirrel.github.com/

**Comment by avaidyam** [comment]
AHAHAHHAHAHAHA that's hilarious. xD what programmer humor. anyway, back to
fixing bugs in my PRs.

**Pull request merged**
