### PR TITLE
Correcting sizing issue when drawing button's with text edge insets and

### PR DESCRIPTION
**Pull request by bryanehansen**
...defaulting button title rendering to be vertically aligned. (This is the standard default for OS X and iOS)

### CODE REVIEW

**Comment by jspahrsummers** [comment]
@ShadoFlameX Do you have a screenshot of incorrect vertical text alignment? I haven't noticed it being significantly incorrect for uses of `TUIControl` that I've seen.

:+1: on the insets change, though.

**Comment by bryanehansen** [comment]
Button titleLabel text defaults to top vertical alignment so any button that is much taller than its title Label will show the text at the top of the button, which I would think would not be the style many people would use. I'll get a screen shot in a moment.

**Comment by bryanehansen** [comment]
The button on the left uses the current top alignment default. The button on the right uses middle alignment. I'm sure there is some additional logic involved in this calculation, but its perfectly performant for a dozen buttons or so. I haven't tried with more.

button screenshot

**Comment by jspahrsummers** [comment]
:+1: Just fix the indentation (tabs, not spaces) and we'll be good to go.

@galaxas0 Correctness is more important than performance. We should make it correct before figuring out how to make it performant.

**Comment by jspahrsummers** [comment]
Thanks!

**Pull request merged**
