### PR TITLE
Invert flippedness conditional

### LINKED ISSUE #48: NSTextField hosted in a TUITableViewCell - Text flips during certain animations
This can be seen in the example project:

Steps to reproduce:
- Run the example
- Enter some text in one of the NSTextFields in the table view
- Drag the row below it upward
- The text entered in the NSTextField flips upside down until the re-order animation completes

It can be difficult to see since the problem row slides behind the row being dragged.  It's easier to see if the test you enter is something like "AAAAAAAA", pretty obvious when that flips upside down.

### PR DESCRIPTION
**Pull request by jspahrsummers**
#37 redux.

This fixes #48.

### CODE REVIEW

**Comment by gcox** [comment]
The problem reported in #48 is still apparent in the example project.  Same repro steps.

**Comment by jspahrsummers** [comment]
@gcox Hmm… which version of Mac OS X are you running? I wonder if the behavior differs between 10.7 and 10.8.

**Comment by gcox** [comment]
@jspahrsummers 10.8 right now, I can try on 10.7 in a few hours.  I was using 10.7 when I first created the issue though.  Come to think of it, I think I do remember watching a WWDC video explaining the flipped property was reversed by default in 10.8.

**Comment by jspahrsummers** [comment]
This machine is running 10.7 (I have another one not with me that's 10.8, on which I made the original changes). I'll take another look, just to make sure I followed the repro steps exactly and can compare before and after.

**Comment by jspahrsummers** [comment]
The branch definitely fixes the issue on 10.7. Do you mind trying `master` on 10.8 and seeing if it has the correct behavior?

**Comment by gcox** [comment]
I just tried it, and yes, the master branch behaves correctly on 10.8.  Good times.

**Comment by jspahrsummers** [comment]
Hmm, I'll have to figure out a more robust check that works on 10.7 and 10.8. Closing this for now.

**Pull request closed without merging**
