### PR TITLE
Fixes for TUIAccessibilityElement

### PR DESCRIPTION
**Pull request by lukeman**
Somehow TUIAccessibilityElement was removed or never added to the Xcode project. Secondarily there was a syntax issue with a property. Both of these issues are fixed.

I only noticed this when updating the CocoaPods spec file as each version excludes this file to avoid a compiler error.

### CODE REVIEW

**Comment by jwilling** [comment]
Odd, I thought this was fixed ages ago on the original repo: https://github.com/twitter/twui/commit/b44a6bf91c301819149acd755747bcdf7d5274c8

**Comment by lukeman** [comment]
Oh, interesting. I wonder if that means there are other commits that never made it back to this fork.

Even in the Twitter tree it looks like `TUIAccessibilityElement` never made it into the Xcode project.

**Comment by jwilling** [comment]
Actually the class itself is just a stub. There's no use for it and as a result it is not used at all.

**Comment by avaidyam** [comment]
I'm pretty sure we can remove it-- the whole TwUI accessibility stuff is a mess at the moment.

**Comment by CodaFi** [comment]
@galaxas0 If you feel like that, then remove it, fix what breaks, then submit a pull request.  A little less talk, and a little more action!!  :)

**Comment by avaidyam** [comment]
@CodaFi Ahh, yeahh =___= I've got a lot of talk to work on. I'm still working on some standard controls and things to add to TwUI-- especially that navigation system I was talking about. I'll just pop in a commit for this. Expect something next week? :D

**Comment by jspahrsummers** [comment]
I haven't looked too much into the accessibility stuff that's already implemented in TwUI, but I agree with @jwilling and @galaxas0 that this class seems not to be used at all and therefore should be removed.

I'd rather do that than keep around a useless stub.

**Comment by avaidyam** [comment]
https://github.com/github/twui/pull/74 <-- here you go! I've also renamed the example project folder to something simpler. But no other changes yet.

**Comment by jwilling** [comment]
This can be closed due to commit a482226cdc.

**Pull request closed without merging**
