### PR TITLE
Basic bridging into AppKit with TUIViewNSViewContainer

### PR DESCRIPTION
**Pull request by jspahrsummers**
This expands `TUIViewNSViewContainer` to actually do things, and refactors a lot of surrounding classes to add the infrastructure to support it. I'm not attached to the naming at all – I was simply following what was already there.

I've tested this with text entry in the example app. Also, the original code was thoroughly tested, so I don't expect many bugs to crop up.

Most of the code for this was lifted (legally) from [Velvet](https://github.com/bitswift/Velvet), with a note to that effect added to the LICENSE file.

### CODE REVIEW

**Comment by jspahrsummers** [comment]
Found some major bugs. Closing this temporarily.

**Comment by jspahrsummers** [comment]
Still have a little bit of glitchiness with `NSViews` in `TUITableViewCells` that are being reordered, but the bulk of the work is ready for use.

**Comment by jwilling** [comment]
@jspahrsummers Are you planning on porting `VELabel` over as well?

**Comment by jspahrsummers** [comment]
@jwilling I wasn't planning on it – I'm trying to keep this to the bare minimum for bridging.

**Comment by avaidyam** [comment]
@jspahrsummers do you plan on bridging the constraint system i'm pulling into the github/dev fork?

**Comment by jspahrsummers** [comment]
@galaxas0 The way I'm approaching bridging AppKit and TwUI (which follows the same philosophy I used in Velvet) is that, conceptually, you're either in the AppKit world or the TwUI world. The only real overlap between the two is at predefined bridging points, which right now are just `TUINSView` and `TUIViewNSViewContainer`.

I mention this because it means that the "bridging" should really be as minimalistic as possible, with an intense focus on getting those bridging points working perfectly, rather than trying to get the whole of each framework interacting with the whole of the other.

With regard to a constraints system specifically, a constraint between an AppKit view and a TwUI view can be imitated by actually applying a constraint between the `NSView` and the `TUINSView`, or a `TUIView` and the `TUIViewNSViewContainer`. Then, the host views should take care of automatically adjusting their (bridged) root view, just as if the constraint were attached to the latter directly.

**Comment by avaidyam** [comment]
That makes a lot more sense, thank you! So the container is like the gate between the two.

**Comment by jspahrsummers** [comment]
@galaxas0 Yep, exactly.

**Comment by jspahrsummers** [comment]
Replaced by #11. (Changed the base branch to `master`.)

**Pull request closed without merging**
