### PR TITLE
Bug fixes and KVO/Notifications!

### PR DESCRIPTION
**Pull request by avaidyam**
I added `TUITextRenderer` notifications, `TUINSView` KVO properties, and fixed a few window dragging/placing glitches. I also removed the rounded mask on the `TUITextField` because it was unnecessary - especially with the `drawFrame` property.

Since i'm new to Github, and obviously cannot follow the instructions for it, please pull this request AFTER the one with the removed stub classes and renamed example folder.

### CODE REVIEW

**Comment by jspahrsummers** [comment]
This PR contains several independent changes. Can you please create separate branches and pull requests for each logical change? [git cherry-pick](http://git-scm.com/docs/git-cherry-pick) will allow you to pick the commits you want for each branch.

**Comment by avaidyam** [comment]
Oh, but I did do that..... these are all general fixes to TwUI?

**Comment by jspahrsummers** [comment]
"General fixes" have logical groupings too.

Here are some hypothetical separate branches that could be reviewed independently:
- `TUITextRenderer` notifications
- `TUINSView` KVO properties
- Window dragging/placing glitches
- `TUITextField` rounded mask removal

**Comment by avaidyam** [comment]
Oh, I see what you meant. My bad! I'll do that right now.

**Pull request closed without merging**
