### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by lorenbrichter**
Two little changes for @2x stuff.

### CODE REVIEW

**Comment by jwilling** [comment]
And it begins.

**Comment by avaidyam** [comment]
Why, hello there! Since you're pretty much the creator of TwUI, please take a look at my issue detailing new features and updates :D thanks, in advance :D

**Comment by joshaber** [comment]
:metal:

**Comment by avaidyam** [comment]
Oh, hey, joshaber, The Core Layout code is done- it's in the original issue I opened for it.

**Comment by joshaber** [comment]
@galaxas0 Could you open a PR for it please? Thanks!

**Comment by avaidyam** [comment]
..... time to figure out how to add files without pushing a change in github.... =___=

By the way, is it just you and twitter that have push rights to the main fork?

**Comment by avaidyam** [comment]
Yep, Pull Request created. It's about 60% done at best, but that's what the community is for :]

**Pull request merged**
