### PR TITLE
TUIPanel + TUIPopover

### PR DESCRIPTION
**Pull request by avaidyam**
TUIPanel mimics the new 10.8 'select a photo' panel in Messages.app, and TUIPopover has been nearly redone to match the Lion style.

### CODE REVIEW

**Comment by jspahrsummers** [comment]
Looks like this won't merge cleanly. Can you merge `master` into your branch and resolve any conflicts?

**Comment by avaidyam** [comment]
Sure! Will do as soon as I push a really big, cool commit. Then merge, then you can do your amazingly thorough code review xD I'm sure I have more bad `return` formatting.

**Comment by jspahrsummers** [comment]
@galaxas0 If this isn't ready yet, you could create a branch from github/twui for the constraints stuff you want to get in:

```
$ git checkout -b github/twui constraints-fixes
$ git push -u REMOTE constraints-fixes
```

Where `REMOTE` is whatever you've named the remote corresponding to your fork (`origin` or something else). Then, you can open a pull request specifically from that branch.

**Comment by avaidyam** [comment]
I think this should go through fine now...

**Comment by jspahrsummers** [comment]
This seems pretty big and combines several unrelated features. Can you create separate pull requests for each one, and include a description and rationale for each? (This could be done by moving commits to new branches with `git cherry-pick`.)

I'm going to go ahead and close this on that basis, but feel free to ask if you have any questions about splitting up the work.

**Comment by avaidyam** [comment]
Aaahhh, there's so much to git I don't know! Well, I'll cherry-pick them and add them to separate branches first.

**Pull request closed without merging**
