### PR TITLE
Unified CGColor <-> NSColor methods across 10.6 to 10.8.

### PR DESCRIPTION
**Pull request by avaidyam**
As the title states.

### CODE REVIEW

**Comment by jspahrsummers** [comment]
This was intentionally not done because we don't want to clobber the built-in functionality on 10.8. We can't guarantee that ours has the same semantics.

**Comment by avaidyam** [comment]
Then how about we forward these calls to the original 10.8 calls if we know we're on 10.8? That would mean one call: `.CGColor` would service 10.6 and 10.7 through its built in fallback method, and on 10.8, it would forward to the "official" method. This would keep cohesiveness and retain 10.8 semantic compatibility.

**Comment by jspahrsummers** [comment]
I don't understand how that solves the problem I described. The issue is that `tui_CGColor` may behave differently from the built-in `CGColor` property (and the same with the constructor) – especially around pattern colors. In order to ensure predictable behavior across OS versions, we can't unify them.

**Comment by avaidyam** [comment]
Alright, that makes sense, but it seems more cumbersome to the programmer. How would we then replicate 10.8's API as close as possible? It seems like that's the issue here.

**Comment by jspahrsummers** [comment]
It's already reasonably close. We're just unable to guarantee the same semantics because we don't know the actual implementation of the 10.8 methods. This is a shitty situation, but not really a solvable problem.

**Comment by avaidyam** [comment]
Would it be possible to run unit tests to see how "close" we are? As it is, my production application sees no issues using the `tui_` methods and blending in with Cocoa on 10.8. Sorry, I just don't like "ugly" API bits. Somewhere in the back of my mind, I think the API should be as "beautiful" as the UI itself. :P

**Comment by jspahrsummers** [comment]
Knowing how "close" we are would require the same knowledge of the implementation details. If we knew _all_ of the edge cases to test and how exactly they should behave on 10.8, we'd be able to write an identical implementation anyways. So it's the same problem.

**Comment by avaidyam** [comment]
Well, I'll leave it at that, then. Oh well.

**Pull request closed without merging**
