### PR TITLE
TUINavigationController

### PR DESCRIPTION
**Pull request by CodaFi**
AppKit always sorely needed a way to manage multiple view controllers, but now TwUI has one!  TUINavigationController is based heavily on UINavigationController, and as such, borrows lots of code from [Chameleon's](http://chameleonproject.org/) UINavigationController implementation (duly noted in the header). 

There is no UI component to the class, seeing as the Mac already has the top bar of an NSWindow, and there's no need to ugly-up the framework with a TUINavigationBar class.

A demonstration of the class can be found [here](https://github.com/CodaFi/TUINavigationController).

### CODE REVIEW

**Comment by avaidyam** [comment]
@CodaFi You sir, are quite amazing. I was just writing this, with an amazing implement for navigation stacks, multiple navigation methods, and more. Thank you for taking a heavy load off of me!

**Comment by CodaFi** [comment]
@galaxas0 Thank you.  Any way you were working on custom push animations? ==fingers crossed==

**Comment by avaidyam** [comment]
Custom push animations? That's just the start of it! One `TUINavigationStack` holds your _tree_ of navigation, and you can pick from a `TUINavigationBar`, a `TUINavigationSourceList`, a `TUINavigationPage` and more! The bar is the usual one you know from iOS, the source list is an iTunes-esque source list, but better, and the navigation page is a custom _gesture-based_ navigation system. That one's speshul. :3

**Comment by avaidyam** [comment]
Oh, I forgot to mention the cool-as-heck door transition. :D
EDIT: You may also want to merge with upstream.

**Comment by CodaFi** [comment]
OK, I've taken a crack at a custom animation block.  The example has been updated to reflect this.

**Comment by avaidyam** [comment]
Wow, even easier for me! Thanks so much! :D 
You still might want to merge upstream, however.

**Comment by CodaFi** [comment]
I prefer that version of TwUI (with the example) to not merge.  It's my own private laboratory.

**Comment by avaidyam** [comment]
Ah, I had one of those going a while back. If you like it that way, sure!

**Comment by jwilling** [comment]
As it borrows actually quite a lot of code from Chameleon (as you noted), it would be great to get @BigZaphod to pop in here giving an a-ok on this.

**Comment by jspahrsummers** [comment]
In addition to @jwilling's note, please also check out the [style guide](https://github.com/github/objective-c-conventions) for new contributions. In particular, the indentation in this pull request needs to be 100% tabs.

**Comment by matpaul** [comment]
@CodaFi in your example, if you hold shift and then quickly switch views then at some point will be a black screen, any ideas how to fix it?)

**Comment by jwilling** [comment]
@realmatpos Because the the animation durations are [hard coded](https://github.com/github/twui/pull/102/files#L3R299).

**Comment by BigZaphod** [comment]
This is fine with me. :)

**Comment by CodaFi** [comment]
@BigZaphod Thanks so much for the go-ahead!  

@jspahrsummers, The latest commit should match the style guide a lot more this time.

**Comment by avaidyam** [comment]
@CodaFi Use the cool mailbox icon! :D it's like this ":mailbox_with_mail" but with another : at the end. /jokes. :+1:

**Comment by CodaFi** [comment]
I'm closing this due to an issue with git on my downstream Repo, but it will be resubmitted.

**Pull request closed without merging**
