### PR TITLE
Feature freeze

### PR DESCRIPTION
**Pull request by jspahrsummers**
This affects everything after the currently open PRs.

[CONTRIBUTING](https://github.com/github/twui/blob/feature-freeze/CONTRIBUTING.md)
[README](https://github.com/github/twui/blob/feature-freeze/README.md)

@joshaber @dannygreg @alanjrogers @jwilling @CodaFi @galaxas0

### CODE REVIEW

**Comment by dannygreg** [comment]
Feels like we need to put some kind of reasoning in place? Suggest an alternative fork maybe?

Could possibly also add a link to Rebel.

**Comment by jspahrsummers** [comment]
Will mention stuff about Rebel.

> Suggest an alternative fork maybe?

Don't know which one this would be.

**Comment by jspahrsummers** [comment]
:ophiuchus:

**Comment by avaidyam** [comment]
@jspahrsummers Would it be alright to redirect to my fork of twui? @jwilling and @CodaFi already have write privileges on that fork and I don't plan on treating it differently from the github fork.

**Comment by jwilling** [comment]
@jspahrsummers :+1: to this. 

@galaxas0 I actually don't use TwUI any more, so I know that personally I won't be contributing to any more TwUI forks moving forward.

**Comment by avaidyam** [comment]
@jwilling Alright, I wasn't holding you to anything :]

I'm just suggesting that since I actively use TwUI and am appending features to it in many, many PRs, as @dannygreg stated, my fork could be linked.

**Comment by jspahrsummers** [comment]
I would prefer not to endorse a specific fork, especially because forks may become more and less active over time. We'd essentially be duplicating the functionality of [the network graph](https://github.com/twitter/twui/network), but manually.

**Comment by avaidyam** [comment]
That's perfectly fine. I was just noting it in response to @dannygreg. Perhaps instead offer a link to the network graph? "If you'd like to find an active fork of TwUI, check the network graph: [link]" or so. I think at the very least, the changes should be pushed upstream to twitter/twui and a message left there too (it's been abandoned there as well...)

**Comment by jspahrsummers** [comment]
:full_moon:

**Comment by avaidyam** [comment]
So I guess that's that for the feature PRs! By the way @jspahrsummers, is that a lemon..?

**Comment by jspahrsummers** [comment]
@galaxas0 You can mouse over it to see the emoji text used. :P

**Comment by avaidyam** [comment]
@jspahrsummers OH! So it's a full moon. That's neat, gotta learn more of these emojis. :panda_face:

**Comment by CodaFi** [comment]
@jspahrsummers :+1:

**Comment by joshaber** [comment]
:feelsgood:

**Pull request merged**
