### PR TITLE
TUIPanel!

### PR DESCRIPTION
**Pull request by avaidyam**
An NSPanel clone with auto-TUIView support that mimics the Messages.app 'Set Picture' window in 10.8.
It doesn't have sheet support yet, and I can't figure out for the life of me how to clip a view's corners (without CALayer intervention, if possible), and I think CGSPrivate died in 10.8, so I can't test window blurring.

But it works, it's non-obtrusive, and I use it in my app.

### CODE REVIEW

**Comment by jspahrsummers** [comment]
I don't have the Messages.app beta, so can you explain what this provides over `NSPanel`?

**Comment by avaidyam** [comment]
A custom panel that looks like this: http://oi49.tinypic.com/2yy78y0.jpg
which supports setting the rootView without worrying about TUINSView, and still supports plain NSView subviews.

**Comment by jspahrsummers** [comment]
I think this could go either way with respect to TwUI's scope, but I'm going to lean toward a smaller framework whenever possible, so I think this is just barely out of scope.

I've created a new [Additions wiki page](https://github.com/github/twui/wiki/Additions), though, where you can feel free to add links to stuff like this.

**Comment by avaidyam** [comment]
I guess that makes sense too :P But these two pull requests were the only ones not integrated into TwUI, so the rest should be more applicable. But how did TUIPopover make it in? Doesn't seem like that's directly Core Animation related...?

**Comment by avaidyam** [comment]
So what DOES qualify for a pull request for TwUI?

**Comment by jspahrsummers** [comment]
I'll add some guidelines to the wiki one of these days, but I'd say one of three things:
1. It fixes some functionality that is already in TwUI. This might be a bug, or something not working as expected.
2. It's something so basic or important that TwUI really should have it (constraints are a great example).
3. It has to integrate with TwUI internals, and so can't easily be done outside of the framework. This one is the most ambiguous, because interesting things may match this criterion, but still be way out of scope. In some cases, a fork might be more appropriate. Use your best judgment.

**Comment by avaidyam** [comment]
So, rather than what the `README.md` states about TwUI being an entire framework, is it more like a 'jumpstart' framework that gives you support in building such UI components?

**Comment by jspahrsummers** [comment]
@galaxas0 Not sure where you're referring to in the README. TwUI should contain the basic components that almost any application will need (e.g., table views, text editing, etc.), but more advanced stuff may not be used by every application, and thus would end up bloating the framework if we included all of it.

Keep in mind that, unlike AppKit or UIKit, TwUI applications have to include the entire framework in the bundle, so size matters.

**Comment by avaidyam** [comment]
Alright, that clears it up then. So, do modal windows and alert views classify into that, so I can pull request for that?

**Comment by jspahrsummers** [comment]
Both of those things can be done by using `TUINSView` in an AppKit window or alert, can't they?

**Comment by avaidyam** [comment]
But doesn't that go for `TUIPopover` as well? ;]

**Comment by jspahrsummers** [comment]
@galaxas0 `TUIPopover` was created because `NSPopover` wasn't available on 10.6. Popovers are very often used when available, so it was considered worth it to mirror `NSPopover`.

**Comment by avaidyam** [comment]
Oh, that makes sense then. Alright, I'll pick out the best of my TwUI clone's internals that make sense to contribute then :]

**Comment by jspahrsummers** [comment]
Thanks. Let me know if you have any further questions. :)

**Comment by avaidyam** [comment]
Alright, will do! Do we also need a navigation controller in TwUI? That seems essential. I have one I could refactor to ARC and add in.

**Comment by jspahrsummers** [comment]
Navigation components are useful, but the problem with a "navigation controller" on Mac OS X is that there's no idiomatic or standardized way to implement one (unlike iOS). Every app does it differently, and the solution to one app may not work for another. For example, document-based apps and single-window apps might need vastly different approaches to navigation.

**Comment by avaidyam** [comment]
Well, how about we implement a multitude of approaches to this? The first one I can think of would be modal sheets, which already exists, the second would be like UINavigationController, which I've got, the third could be like a side-tab bar or something. 

I think what we should do with TwUI is try to allow a multitude of approaches, but all packaged into one box. For example, something like a TUINavigationMarker for each 'page' (really a view), and you could use a TUINavigationBar/Controller to move through markers, or perhaps an android-like Action Bar, or maybe a Twitter-like sliding page approach. So, in essence, the same kind of 'kit' for layout constraints, but for navigation markers.

On another note, we need a consortium-like thing for TwUI. Would be pretty handy :D

**Comment by jspahrsummers** [comment]
I don't think it's appropriate to bundle "a multitude of approaches" into TwUI. TwUI should include standardized components that almost any app will use, and not have to choose between. The alternative is framework bloat, which we don't want (see my comment about bundle size above).

I'd much prefer to keep different approaches in one or more other repositories.

**Comment by avaidyam** [comment]
Oh, I understand that, I meant create something like a marker system so anyone can implement the approach that works best for them, using a protocol and a view marker. It's really sketchy right now, but I'll think about it.

**Comment by avaidyam** [comment]
On that note, please do take a look at this: https://github.com/twitter/twui/issues/122

**Pull request closed without merging**
