### PR TITLE
Fix TUINSView not being deallocated

### PR DESCRIPTION
**Pull request by luosheng**
This can be reproduced by following steps:
1. In `ExampleAppDelegate.m`, change 
   `[tableViewWindow setReleasedWhenClosed:FALSE]` to 
   `[tableViewWindow setReleasedWhenClosed:TRUE]`.
2. In `TUINSView.m`, add a breakpoint to the `dealloc` method.
3. Run the example, and close the table view window.

The breakpoint is expected to be hit, however it is not.

It seems to be a bug introduced by AppKit bridging, when the following line is invoked in the `setUp` method of `TUINSView`:

``` objective-c
self.appKitHostView.layer.layoutManager = self;
```

The layer retains the layoutManager, which is the instance of TUINSView, and never has a chance to release it. And that's why the instance is not deallocated.

I fixed it by adding an observer to `NSWindowWillCloseNotification`, where I could set layer's layoutManager to `nil` to make the layer release the TUINSView's instance.

### CODE REVIEW

**Comment by jspahrsummers** [comment]
Wow, nice catch!

You could probably do this with `viewWillMoveToWindow:` and `viewDidMoveToWindow`, though – setting the layout manager when moving to a non-`nil` window, and removing it when moving to `nil` – which would avoid the need for more notification handlers here.

**Comment by luosheng** [comment]
OK, I've made the changes.

**Comment by jspahrsummers** [comment]
:sparkles: Thanks!

**Comment by avaidyam** [comment]
Wow that's amazing, I caught that a minute ago too-- as well as the fact that when you add a `TUIView` to a `TUINSView` which has just been added to an `NSWindow` shortly afterwards, the `TUIViewDidMoveToWindowNotification` is called multiple times.

**Pull request merged**
